name: Publish

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
          egistry-url: https://registry.npmjs.org/

      - name: NPM Install, Build, Build React and Test
        run: |
          npm install
          npm run eslint
          npm run test
          npm run build
          npm run build:react
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build and Deploy to Storybook
        run: |
          npm run storybook:build
          npm run storybook:deploy
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          branch: master
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/git
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
